version: '3.8'
services:
  mysql_dev:
    image: mysql:5.7
    platform: linux/amd64
    container_name: worksheet_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DEV_DB_NAME}
      MYSQL_USER: ${DEV_DB_USER}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "${DEV_DB_PORT}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  mysql_test:
    image: mysql:5.7
    platform: linux/amd64
    container_name: worksheet_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_dev_data:
  mysql_test_data: 